---
title: "Sentiment Analysis during the Covid"
subtitle: "727 Final Project"
author: "Group 8 - Mingqian Zheng, Yuyao Liu"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


```{r}
if(!require(rtweet)) install.packages('rtweet')
if(!require(tidyverse)) install.packages('tidyverse')
if(!require(dplyr)) install.packages('dplyr')
if(!require(tidytext)) install.packages('tidytext')
if(!require(ggmap)) install.packages('ggmap')
if(!require(rjson)) install.packages('rjson')
if(!require(maps)) install.packages('maps')
if(!require(gridExtra)) install.packages('gridExtra')
if(!require(textshape)) install.packages('textshape')
if(!require(syuzhet)) install.packages('syuzhet')
```

```{r}

library(rtweet)
library(tidyverse)
library(dplyr)
library(tidytext)
library(ggmap)
library(rjson)
library(maps)
library(gridExtra)
library(syuzhet)
```






```{r}
if(!require(gtrendsR)) install.packages('gtrendsR')
library(gtrendsR)

searchtime = "2022-11-20 2022-12-08"

worldwide_trend <- gtrends(c("World Cup"), time = searchtime, low_search_volume = TRUE)

us_worldcup <- gtrends(c("World Cup"), geo = "US", time = searchtime, low_search_volume = TRUE)
str(us_worldcup)
str(worldwide_trend)
```

```{r}
library(datasets)
data(countries)
summary(countries)
countries_info <- data.frame(countries)
countries_info

str(state.x77)
state_name <- dimnames(state.x77)[[1]]
state_name

state_info <- as_tibble(state.x77)
state_info$name <- state_name
state_info$abb <- state.abb
state_info
```


```{r}
# if(!require(usdata)) install.packages('usdata')
# library(usdata)
# 
# data(county)
# unique(county$state)
# 
# county <- county %>% 
#   group_by(state) %>%
  
```




```{r}
if(!require(usa)) install.packages('usa')
library(usa)

facts # population data is for 2019 
facts <- facts %>%
  select(name, population)
facts
```



```{r}
if(!require(scales)) install.packages('scales')
library(scales)

us_regions_hit <- us_worldcup$interest_by_region %>%
  rename(state=location, hits=hits)
us_regions_hit <- us_regions_hit %>%
  inner_join(facts, by=c('state'='name')) 
us_regions_hit
us_pop <- sum(us_regions_hit$population)
us_pop


## add pop weight 
## The search volume is on a 100-point-scale.
us_regions_hit <- us_regions_hit %>%
  mutate(pop_w = population/us_pop) %>%
  mutate(hits_w = hits * pop_w) %>%
  select(state, hits_w, hits) %>%
  arrange(desc(hits_w)) %>%
  mutate(hits_rescale = as.integer(rescale(hits_w, to=c(0,100))))

us_regions_hit
```


# plot the us heat map 

```{r}
# plot a us map using values of search volumn 

if(!require(usmap)) install.packages('usmap')
library(usmap)

plot_usmap(data = us_regions_hit, values = "hits_rescale", color = "#56042C") + 
  scale_fill_continuous(low="white", high="#56042C", name = "Search Volumn", label = scales::comma) + 
  labs(title="Google trends of 'World Cup from 2022-11-20 to 2022-12-08'") +
  theme(legend.position = "right")
```




```{r}
world_country_hit <- worldwide_trend$interest_by_country
world_country_hit
plot(us_worldcup)
plot(worldwide_trend)

world_country_hit <- world_country_hit %>%
  select(location, hits) %>%
  rename(region=location, hits=hits)
```


```{r}
top_10_regions <- us_regions_hit[1:10,]
top_10_regions
```








